apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: srv-reservation
spec:
  template:
    spec:
      containerConcurrency: 20
      containers:
      - command:
        - reservation
        env:
        - name: DLOG
          value: DEBUG
        image: teresaliuchang/hotel_demo:v1.7
        name: hotel-reserv-reservation
        ports:
          - name: h2c
            containerPort: 8086
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 1000m
